const $=id=>document.getElementById(id);
const money=n=>'RM '+Number(n||0).toLocaleString('en-MY',{minimumFractionDigits:2,maximumFractionDigits:2});
const store={get:(k,d=[])=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d)),set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
let editingQuoteId=null;

document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));
document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.go)));
function showPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===id));$(id).classList.add('active');refreshAll()}
function customers(){return store.get('ks_customers',[])} function quotes(){return store.get('ks_quotes',[])}
function activeCustomerId(){return localStorage.getItem('ks_active_customer')||''} function activeCustomer(){return customers().find(c=>c.id===activeCustomerId())}
function customerName(id){return customers().find(c=>c.id===id)?.company||''}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}

function contactRow(c={}){const row=document.createElement('div');row.className='contact-row';row.innerHTML=`<div><label>Prefix</label><select class="c-prefix"><option${c.prefix==='Mr.'?' selected':''}>Mr.</option><option${c.prefix==='Ms.'?' selected':''}>Ms.</option><option${c.prefix==='Mrs.'?' selected':''}>Mrs.</option><option${c.prefix==='Dr.'?' selected':''}>Dr.</option><option${c.prefix==='Ir.'?' selected':''}>Ir.</option><option${c.prefix==='Dato\''?' selected':''}>Dato'</option></select></div><div><label>Name</label><input class="c-name" value="${esc(c.name||'')}"></div><div><label>Phone</label><input class="c-phone" value="${esc(c.phone||'')}"></div><div><label>Email</label><input class="c-email" type="email" value="${esc(c.email||'')}"></div><button type="button" class="btn danger remove-contact">Remove</button>`;row.querySelector('.remove-contact').onclick=()=>row.remove();$('contactEditor').appendChild(row)}
function getContacts(){return [...document.querySelectorAll('.contact-row')].map(r=>({prefix:r.querySelector('.c-prefix').value,name:r.querySelector('.c-name').value.trim(),phone:r.querySelector('.c-phone').value.trim(),email:r.querySelector('.c-email').value.trim()})).filter(c=>c.name||c.phone||c.email)}
function saveCustomer(){const company=$('company').value.trim();if(!company)return alert('Company name is required.');let arr=customers(),id=$('customerId').value||crypto.randomUUID();const c={id,company,companyPhone:$('companyPhone').value,address:$('address').value,project:$('customerProject').value,reference:$('customerReference').value,notes:$('customerNotes').value,contacts:getContacts()};const i=arr.findIndex(x=>x.id===id);if(i>=0)arr[i]=c;else arr.push(c);store.set('ks_customers',arr);localStorage.setItem('ks_active_customer',id);clearCustomer();refreshAll();alert('Customer saved and selected as active customer.')}
function clearCustomer(){['customerId','company','companyPhone','address','customerProject','customerReference','customerNotes'].forEach(id=>$(id).value='');$('contactEditor').innerHTML='';contactRow()}
function editCustomer(id){const c=customers().find(x=>x.id===id);if(!c)return;$('customerId').value=c.id;$('company').value=c.company||'';$('companyPhone').value=c.companyPhone||'';$('address').value=c.address||'';$('customerProject').value=c.project||'';$('customerReference').value=c.reference||'';$('customerNotes').value=c.notes||'';$('contactEditor').innerHTML='';(c.contacts?.length?c.contacts:[{}]).forEach(contactRow);showPage('customers')}
function selectCustomer(id){localStorage.setItem('ks_active_customer',id);refreshAll()}
function deleteCustomer(id){if(confirm('Delete this customer?')){store.set('ks_customers',customers().filter(x=>x.id!==id));if(activeCustomerId()===id)localStorage.removeItem('ks_active_customer');refreshAll()}}
function refreshCustomers(){const arr=customers(),active=activeCustomerId();$('customerRows').innerHTML=arr.map(c=>`<tr${c.id===active?' class="active-customer"':''}><td>${esc(c.company)}</td><td>${esc(c.project||'')}</td><td>${(c.contacts||[]).length}</td><td>${c.id===active?'<span class="badge won">Selected</span>':`<button class="btn green" data-select-c="${c.id}">Select</button>`}</td><td><button class="btn secondary" data-edit-c="${c.id}">Edit</button> <button class="btn danger" data-del-c="${c.id}">Delete</button></td></tr>`).join('')||'<tr><td colspan="5" class="muted">No customers yet.</td></tr>';document.querySelectorAll('[data-select-c]').forEach(b=>b.onclick=()=>selectCustomer(b.dataset.selectC));document.querySelectorAll('[data-edit-c]').forEach(b=>b.onclick=()=>editCustomer(b.dataset.editC));document.querySelectorAll('[data-del-c]').forEach(b=>b.onclick=()=>deleteCustomer(b.dataset.delC));const opts='<option value="">Select customer</option>'+arr.map(c=>`<option value="${c.id}">${esc(c.company)}</option>`).join('');const old=$('qCustomer').value;$('qCustomer').innerHTML=opts;$('qCustomer').value=old;const a=activeCustomer();$('activeCustomerBanner').className=a?'notice active-customer':'notice';$('activeCustomerBanner').innerHTML=a?`Active customer: <b>${esc(a.company)}</b>${a.project?` · Project: ${esc(a.project)}`:''}${a.reference?` · Ref: ${esc(a.reference)}`:''}`:'Select an active customer from the Customer page first.'}

function nextQuoteNo(){const d=new Date(),yy=String(d.getFullYear()).slice(-2),mm=String(d.getMonth()+1).padStart(2,'0'),seq=String(quotes().length+1).padStart(4,'0');return `R-${yy}${mm}-${seq}`}
function calcTotal(){const total=(+$('qQty').value||0)*(+$('unitPrice').value||0)*(1-(+$('discount').value||0)/100);$('quoteTotal').textContent=money(total);return total}
function saveQuote(){if(!$('qCustomer').value)return alert('Customer is required.');const q={id:editingQuoteId||crypto.randomUUID(),no:$('quoteNo').value||nextQuoteNo(),date:$('qDate').value,status:$('qStatus').value,customerId:$('qCustomer').value,project:$('qProject').value,yourRef:$('qYourRef').value,preparedBy:$('preparedBy').value,model:$('qModel').value,qty:+$('qQty').value,unitPrice:+$('unitPrice').value,discount:+$('discount').value,delivery:$('delivery').value,validity:$('validity').value,description:$('description').value,payment:$('payment').value,remarks:$('remarks').value,total:calcTotal()};let arr=quotes(),i=arr.findIndex(x=>x.id===q.id);if(i>=0)arr[i]=q;else arr.unshift(q);store.set('ks_quotes',arr);editingQuoteId=q.id;$('quoteNo').value=q.no;refreshAll();alert('Quotation saved.')}
function loadQuote(id){const q=quotes().find(x=>x.id===id);if(!q)return;editingQuoteId=id;const map={quoteNo:'no',qDate:'date',qStatus:'status',qCustomer:'customerId',qProject:'project',qYourRef:'yourRef',preparedBy:'preparedBy',qModel:'model',qQty:'qty',unitPrice:'unitPrice',discount:'discount',delivery:'delivery',validity:'validity',description:'description',payment:'payment',remarks:'remarks'};Object.entries(map).forEach(([id,k])=>$(id).value=q[k]??'');calcTotal();showPage('quotation')}
function deleteQuote(id){if(confirm('Delete this quotation?')){store.set('ks_quotes',quotes().filter(x=>x.id!==id));refreshAll()}}
function newQuote(){editingQuoteId=null;['qProject','qYourRef','qModel','description','remarks'].forEach(id=>$(id).value='');$('quoteNo').value=nextQuoteNo();$('qDate').value=new Date().toISOString().slice(0,10);$('qStatus').value='Draft';$('qQty').value=1;$('unitPrice').value=0;$('discount').value=0;const a=activeCustomer();if(a){$('qCustomer').value=a.id;$('qProject').value=a.project||'';$('qYourRef').value=a.reference||''}calcTotal()}
function refreshQuotes(){const arr=quotes();$('quoteRows').innerHTML=arr.map(q=>`<tr><td>${esc(q.no)}</td><td>${esc(q.date)}</td><td>${esc(customerName(q.customerId))}</td><td>${esc(q.project)}</td><td>${esc(q.model)}</td><td>${money(q.total)}</td><td><span class="badge ${q.status.toLowerCase()}">${q.status}</span></td><td><button class="btn secondary" data-open-q="${q.id}">Open</button> <button class="btn danger" data-del-q="${q.id}">Delete</button></td></tr>`).join('')||'<tr><td colspan="8" class="muted">No quotations yet.</td></tr>';document.querySelectorAll('[data-open-q]').forEach(b=>b.onclick=()=>loadQuote(b.dataset.openQ));document.querySelectorAll('[data-del-q]').forEach(b=>b.onclick=()=>deleteQuote(b.dataset.delQ));$('recentQuotes').innerHTML=arr.slice(0,5).map(q=>`<tr><td>${q.no}</td><td>${esc(customerName(q.customerId))}</td><td>${esc(q.model)}</td><td>${money(q.total)}</td><td>${q.status}</td></tr>`).join('')||'<tr><td colspan="5" class="muted">No quotations yet.</td></tr>';$('mCustomers').textContent=customers().length;$('mQuotes').textContent=arr.length;$('mValue').textContent=money(arr.reduce((s,q)=>s+q.total,0));$('mPending').textContent=arr.filter(q=>['Draft','Sent'].includes(q.status)).length}
function refreshAll(){refreshCustomers();refreshQuotes()}

window.addEventListener('message',function(event){if(!event.data||event.data.type!=='KEYSUITE_ADD_SELECTION')return;const p=event.data.payload||{},a=activeCustomer();if(!a){alert('Please select a customer first.');showPage('customers');return}showPage('quotation');$('qCustomer').value=a.id;$('qProject').value=a.project||'';$('qYourRef').value=a.reference||'';$('qModel').value=p.model||'';$('qQty').value=1;const mat=$('pumpMaterial').value,faces=$('sealFaces').value,elast=$('sealElastomer').value;const motor=[p.motor_kw!=null?`${Number(p.motor_kw).toFixed(2)} kW`:'',p.motor_hp!=null?`${Number(p.motor_hp).toFixed(2).replace(/\.00$/,'')} HP`:''].filter(Boolean).join(' / ');$('description').value=['B.G.Reich Vertical Multistage Pump',`Model: ${p.model||'-'}`,`Duty: ${Number(p.flow_m3h||0).toFixed(1)} m³/h @ ${Number(p.head_m||0).toFixed(1)} m`,`Material: ${mat}`,`Mechanical Seal: ${faces}, ${elast}`,`Motor: ${motor}, ${p.motor_voltage||415}V / ${p.motor_phase||'3Ph'} / ${Number(p.frequency_hz||50).toFixed(1)}Hz`,p.speed_rpm!=null?`Speed: ${Math.round(p.speed_rpm)} rpm`:'',p.efficiency!=null?`Pump Efficiency: ${Number(p.efficiency).toFixed(1)}%`:'',p.npshr!=null?`NPSHr: ${Number(p.npshr).toFixed(2)} m`:'',p.connection?`Connection: ${p.connection}`:''].filter(Boolean).join('\n');calcTotal()});

$('addContact').onclick=()=>contactRow();$('saveCustomer').onclick=saveCustomer;$('clearCustomer').onclick=clearCustomer;['qQty','unitPrice','discount'].forEach(id=>$(id).addEventListener('input',calcTotal));$('saveQuote').onclick=saveQuote;$('newQuote').onclick=newQuote;$('printQuote').onclick=()=>window.print();$('saveNotes').onclick=()=>{localStorage.setItem('ks_notes',$('testingNotes').value);alert('Testing notes saved.')};$('testingNotes').value=localStorage.getItem('ks_notes')||'';clearCustomer();newQuote();refreshAll();if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js');
