(() => {
  'use strict';
  let access=null, selectedId='', bound=false, editing=false;
  const byId=id=>document.getElementById(id);
  const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const num=(value,d=2)=>Number(value||0).toLocaleString('en-MY',{minimumFractionDigits:d,maximumFractionDigits:d});
  const isOwner=()=>String(access?.role||window.KEYSUITE_ACCESS?.role||'').toLowerCase()==='owner';
  const categories=()=>window.KEYSUITE_SECURE_DATA?.categories||[];
  const fields=['categoryNameInput','categoryCommissionInput','categorySetDiscountInput','categoryFinalDiscountInput','categoryMarginInput','categoryTransportInput'];
  function message(text,type='info'){const box=byId('categoryMessage');if(!box)return;box.textContent=text||'';box.className=text?`auth-message show ${type}`:'auth-message'}
  function setEditable(on){editing=!!on;const form=byId('categoryForm');form?.classList.toggle('category-form-readonly',!editing);fields.forEach(id=>{const el=byId(id);if(el)el.disabled=!editing});const edit=byId('editCategoryRule');if(edit)edit.style.display=selectedId&&!editing?'inline-block':'none';const save=byId('saveCategoryRule');if(save)save.disabled=!editing}
  function fill(category=null){selectedId=category?.id||'';byId('categoryFormTitle').textContent=category?'Edit Category':'New Category';byId('categoryNameInput').value=category?.name||'';byId('categoryCommissionInput').value=num(Number(category?.commission??.03)*100,2).replace(/,/g,'');byId('categorySetDiscountInput').value=num(Number(category?.set_discount??.068)*100,2).replace(/,/g,'');byId('categoryFinalDiscountInput').value=num(Number(category?.final_discount??.08)*100,2).replace(/,/g,'');byId('categoryMarginInput').value=num(Number(category?.margins?.CHC??category?.factors?.CHC??.38)*100,2).replace(/,/g,'');byId('categoryTransportInput').value=num(category?.transport??30,2).replace(/,/g,'');renderRows()}
  function openCategory(category,forEdit=false){fill(category);setEditable(forEdit);message(forEdit?'Category is ready for editing.':'Saved category loaded. Press Edit to make changes.','info')}
  function newCategory(){fill(null);setEditable(true);message('New category form is ready.','info');setTimeout(()=>byId('categoryNameInput')?.focus(),0)}
  function renderRows(){const body=byId('categoryRows');if(!body)return;const rows=categories();if(!rows.length){body.innerHTML='<tr><td class="category-empty">No pricing categories yet.</td></tr>';return}body.innerHTML=rows.map(category=>`<tr><td><button class="category-name-button ${category.id===selectedId?'active':''}" type="button" data-category-open="${esc(category.id)}">${esc(category.name)}</button></td></tr>`).join('');body.querySelectorAll('[data-category-open]').forEach(button=>button.addEventListener('click',()=>{const category=categories().find(item=>item.id===button.dataset.categoryOpen);if(category)openCategory(category,false)}))}
  function mapRows(rows){return (rows||[]).map(c=>({id:c.id,name:c.category_name,final_discount:Number(c.final_discount||0),set_discount:Number(c.set_discount||0),commission:Number(c.commission||0),margins:{CHC:Number(c.chc_margin??c.chc_factor??0)},factors:{CHC:Number(c.chc_margin??c.chc_factor??0)},transport:Number(c.transport||0)}))}
  async function reload(){const client=window.KeySuiteAuth?.getClient?.();if(!client)return;const {data,error}=await client.from('ks_pricing_categories').select('*').order('category_name');if(error)throw error;const mapped=mapRows(data);const target=window.KEYSUITE_SECURE_DATA?.categories;if(Array.isArray(target))target.splice(0,target.length,...mapped);window.KeySuitePricing?.render?.();return mapped}
  function fieldPercent(id,label){const value=Number(byId(id)?.value);if(!Number.isFinite(value)||value<0||value>=100)throw new Error(`${label} must be from 0% to below 100%.`);return value/100}
  async function save(event){event.preventDefault();if(!editing)return;if(!isOwner()){message('Only the Owner can manage pricing categories.','error');return}const name=byId('categoryNameInput').value.trim(),transport=Number(byId('categoryTransportInput').value);if(!name){message('Category Name is required.','error');return}if(!Number.isFinite(transport)||transport<0){message('Transport must be RM0.00 or more.','error');return}let margin,commission,setDiscount,finalDiscount;try{commission=fieldPercent('categoryCommissionInput','Commission');setDiscount=fieldPercent('categorySetDiscountInput','Set Discount');finalDiscount=fieldPercent('categoryFinalDiscountInput','Final Discount');margin=fieldPercent('categoryMarginInput','CHC Margin')}catch(error){message(error.message,'error');return}const client=window.KeySuiteAuth?.getClient?.();if(!client){message('Supabase is not connected.','error');return}const button=byId('saveCategoryRule'),original=button.textContent;button.disabled=true;button.textContent='Saving…';message('');try{const {error}=await client.rpc('keysuite_manage_pricing_category',{p_category_id:selectedId||null,p_category_name:name,p_chc_margin:margin,p_transport:transport,p_commission:commission,p_set_discount:setDiscount,p_final_discount:finalDiscount});if(error)throw error;const rows=await reload();const saved=(rows||categories()).find(item=>item.name.toLowerCase()===name.toLowerCase());openCategory(saved||null,false);message(`Category “${name}” saved.`,'info')}catch(error){console.error(error);message(`${error.message||error}. Run the V1.16 Supabase migration first.`,'error')}finally{button.disabled=false;button.textContent=original}}
  function cancel(){if(selectedId){const category=categories().find(x=>x.id===selectedId);if(category)openCategory(category,false)}else{const first=categories()[0];if(first)openCategory(first,false);else newCategory()}}
  function bind(){if(bound)return;bound=true;byId('categoryForm')?.addEventListener('submit',save);byId('newPricingCategory')?.addEventListener('click',newCategory);byId('cancelCategoryEdit')?.addEventListener('click',cancel);byId('editCategoryRule')?.addEventListener('click',()=>{if(!selectedId)return;setEditable(true);message('Editing enabled.','info');byId('categoryNameInput')?.focus()})}
  function render(){if(!isOwner())return;renderRows();if(!selectedId&&categories().length)openCategory(categories()[0],false);const notice=byId('categoryAccessNotice');if(notice)notice.innerHTML=`Signed in as <b>${esc(access?.display_name||access?.email||'Owner')}</b>. Select a category to view it, then press Edit to change it.`}
  function init(data,userAccess){access=userAccess||access;bind();render()}
  function pageShown(id){if(id==='categoryManagement')render()}
  window.KeySuiteCategories={init,pageShown,reload,render};
})();
