(() => {
  'use strict';
  let selectedSeries='', frameReady=false, queued=null;
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const products=()=>window.KEYSUITE_SECURE_DATA?.products||[];
  function baseModelName(value){return String(value||'').replace(/^CHC[SN]?\s+/i,'CHC ')}
  function seriesName(model){const m=String(model||'').match(/^CHC\s+(\d+)/i);return m?`CHC ${m[1]}`:'Other'}
  function orderedSeries(){return [...new Set(products().map(p=>seriesName(p.model)).filter(x=>x!=='Other'))].sort((a,b)=>Number(a.split(' ')[1])-Number(b.split(' ')[1]))}
  function options(){return {material:$('productMaterial').value,seal:$('productSeal').value,elastomer:$('productElastomer').value,connection:$('productConnection').value,bare:!!$('productBareShaft').checked}}
  function ensureFrame(){const frame=$('productSelectorFrame');if(frame&&frame.src==='about:blank')frame.src=frame.dataset.src;return frame}
  function send(model,action){const frame=ensureFrame();if(!frame)return;queued={type:'KEYSUITE_PRODUCT_MODEL',model:baseModelName(model),action,options:options()};if(frameReady)frame.contentWindow.postMessage(queued,'*')}
  function renderSeries(){const series=orderedSeries();if(!selectedSeries||!series.includes(selectedSeries))selectedSeries=series[0]||'';$('productSeriesList').innerHTML=series.map(name=>`<button type="button" class="product-series-button ${name===selectedSeries?'active':''}" data-product-series="${esc(name)}">${esc(name)}</button>`).join('');$('productSeriesList').querySelectorAll('[data-product-series]').forEach(b=>b.onclick=()=>{selectedSeries=b.dataset.productSeries;renderSeries();renderModels()})}
  function renderModels(){const query=String($('productModelInput').value||'').trim().toLowerCase();let rows=products().filter(p=>seriesName(p.model)===selectedSeries);if(query)rows=rows.filter(p=>String(p.model).toLowerCase().includes(query));$('productSeriesTitle').textContent=selectedSeries||'Models';$('productModelCount').textContent=`${rows.length} model${rows.length===1?'':'s'}`;$('productModelGrid').innerHTML=rows.length?rows.map(p=>`<div class="product-model-card"><h3>${esc(p.model)}</h3><div class="product-model-actions"><button class="btn secondary" type="button" data-product-view="${esc(p.model)}">View Curve</button><button class="btn green" type="button" data-product-export="${esc(p.model)}">Export PDF</button><button class="btn" type="button" data-product-add="${esc(p.model)}">Add to Quotation</button></div></div>`).join(''):'<div class="product-empty">No matching CHC models.</div>';const grid=$('productModelGrid');grid.querySelectorAll('[data-product-view]').forEach(b=>b.onclick=()=>{const model=b.dataset.productView;$('productCurveTitle').textContent=model;const frame=ensureFrame();const host=$('productCurveHost');if(frame.parentNode!==host)host.appendChild(frame);frame.style.display='block';$('productCurveDialog').showModal();send(model,'view')});grid.querySelectorAll('[data-product-export]').forEach(b=>b.onclick=()=>send(b.dataset.productExport,'export'));grid.querySelectorAll('[data-product-add]').forEach(b=>b.onclick=()=>{if(!window.KeySuiteApp?.ensureQuotationPricingContext?.('add a product to the quotation'))return;send(b.dataset.productAdd,'add')})}
  function render(){const list=$('productModelOptions');if(!list)return;list.innerHTML=products().map(p=>`<option value="${esc(p.model)}"></option>`).join('');renderSeries();renderModels()}
  function pageShown(id){if(id!=='productChc')return;ensureFrame();render()}
  window.addEventListener('message',event=>{if(event.source===$('productSelectorFrame')?.contentWindow&&event.data?.type==='KEYSUITE_PRODUCT_FRAME_READY'){frameReady=true;if(queued)$('productSelectorFrame').contentWindow.postMessage(queued,'*')}})
  document.addEventListener('DOMContentLoaded',()=>{$('productModelInput')?.addEventListener('input',()=>{const exact=products().find(p=>p.model.toLowerCase()===$('productModelInput').value.trim().toLowerCase());if(exact)selectedSeries=seriesName(exact.model);renderSeries();renderModels()});$('closeProductCurve')?.addEventListener('click',()=>$('productCurveDialog')?.close())});
  window.KeySuiteProduct={pageShown,render};
})();
